// Types likely to be generated by various systems, added manually here.

export interface Order {
  id: number;
  orderTotal: number;
  orderDate: string;
  customerEmail: string;
  customerName: string;
  shippingAddress: string;
  lineItems: number[];
}

// The orders api responds with orders that include complete line item objects.
// Some order type are base~ order types (eg., above) while others are extentions (eg., below).
export interface OrderWithLineItems extends Omit<Order, "lineItems"> {
  lineItems: LineItem[];
}

export interface LineItem {
  id: number;
  name: string;
  products: Product[];
}

export interface Product {
  name: string;
}

export interface ProductRequirements {
  [index: string]: number;
}
